import { ArrowRight, CheckCircle2, FileCheck2, LockKeyhole, QrCode, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#071d2b] text-[#f3fbfb]">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[740px] bg-[radial-gradient(circle_at_77%_18%,rgba(62,165,157,.28),transparent_24%),radial-gradient(circle_at_9%_10%,rgba(38,112,150,.22),transparent_27%)]" />
      <nav className="relative mx-auto flex h-20 w-full max-w-7xl items-center justify-between px-6 lg:px-8">
        <Link href="/" className="flex items-center gap-3 text-xl font-extrabold tracking-[-.06em]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#ccf5ea] text-[#15766e] shadow-[0_0_0_6px_rgba(160,236,222,.08)]"><ShieldCheck size={21} /></span>securedocs</Link>
        <div className="hidden items-center gap-7 text-sm font-semibold text-[#a9c6ce] md:flex"><a href="#security" className="transition hover:text-white">Security</a><a href="#workflows" className="transition hover:text-white">Workflows</a><a href="#verification" className="transition hover:text-white">Verification</a></div>
        <div className="flex items-center gap-3"><Link href="/sign-in" className="hidden px-2 text-sm font-bold text-[#d2e7e9] sm:block">Sign in</Link><Link href="/workspace" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#d8f7ed] px-4 text-sm font-extrabold text-[#10394a] shadow-[0_8px_22px_rgba(72,194,170,.22)] transition-transform active:scale-[.97]">Open workspace <ArrowRight size={15} /></Link></div>
      </nav>

      <section className="relative mx-auto grid min-h-[650px] max-w-7xl items-center gap-16 px-6 pb-20 pt-12 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pt-16">
        <div className="max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#2d6571] bg-[#103345]/75 px-3 py-1.5 text-[11px] font-extrabold uppercase tracking-[.14em] text-[#9ce5d4]"><span className="h-1.5 w-1.5 rounded-full bg-[#66d4b9]" /> Evidence that stays trusted</div><h1 className="max-w-xl text-5xl font-extrabold leading-[.98] tracking-[-.075em] text-white sm:text-6xl lg:text-7xl">Document control<br /><span className="text-[#8de1cf]">without blind spots</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-[#abc6ce] sm:text-lg">SecureDocs combines protected document operations, review decisions, public authenticity checks, and audit evidence in one calm operational workspace</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/sign-in" className="inline-flex h-12 items-center gap-2 rounded-xl bg-[#d8f7ed] px-5 text-sm font-extrabold text-[#10394a] shadow-[0_10px_24px_rgba(72,194,170,.18)] transition-transform active:scale-[.97]">Secure your workspace <ArrowRight size={16} /></Link><a href="#workflows" className="inline-flex h-12 items-center rounded-xl border border-[#376472] px-5 text-sm font-bold text-[#d5e6e9] transition hover:border-[#66c8ba] hover:bg-white/5">Explore workflows</a></div><div className="mt-12 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-[#b1cbd1]"><span className="flex items-center gap-2"><CheckCircle2 size={15} className="text-[#7fe0ca]" /> Role-aware control</span><span className="flex items-center gap-2"><CheckCircle2 size={15} className="text-[#7fe0ca]" /> Private document storage</span><span className="flex items-center gap-2"><CheckCircle2 size={15} className="text-[#7fe0ca]" /> Verifiable evidence</span></div></div>
        <div className="relative mx-auto w-full max-w-[590px]"><div className="absolute -inset-8 rounded-full bg-[#43b6a2]/15 blur-3xl" /><div className="relative overflow-hidden rounded-[26px] border border-[#3b6672] bg-[#102e40]/95 p-4 shadow-[0_35px_100px_rgba(0,0,0,.34)]"><div className="flex items-center justify-between border-b border-[#2a5360] px-2 pb-4"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#1d5964] text-[#91e4d2]"><ShieldCheck size={16} /></span><div><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#8aabb5]">SecureDocs</p><p className="text-xs font-bold text-white">Control center</p></div></div><span className="rounded-full bg-[#173f4b] px-2.5 py-1 text-[10px] font-bold text-[#9fe5d7]">Protected</span></div><div className="grid grid-cols-3 gap-3 py-4"><div className="rounded-xl border border-[#275360] bg-[#133749] p-3"><p className="text-[10px] text-[#8daab3]">Documents</p><strong className="mt-1 block text-2xl tracking-[-.06em] text-white">1,248</strong></div><div className="rounded-xl border border-[#275360] bg-[#133749] p-3"><p className="text-[10px] text-[#8daab3]">Verified</p><strong className="mt-1 block text-2xl tracking-[-.06em] text-[#91e4d2]">82.7%</strong></div><div className="rounded-xl border border-[#275360] bg-[#133749] p-3"><p className="text-[10px] text-[#8daab3]">Alerts</p><strong className="mt-1 block text-2xl tracking-[-.06em] text-[#ffd78e]">04</strong></div></div><div className="grid gap-3"><div className="rounded-xl border border-[#285463] bg-[#0d2939] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#153e51] text-[#95d8eb]"><FileCheck2 size={17} /></span><div><p className="text-sm font-bold text-white">Vendor Compliance Agreement</p><p className="mt-1 text-[10px] text-[#91abb4]">Submitted for manager review</p></div></div><span className="rounded-full bg-[#463b22] px-2 py-1 text-[10px] font-bold text-[#ffd77e]">Pending</span></div></div><div className="rounded-xl border border-[#285463] bg-[#0d2939] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#174e4a] text-[#8fe4d2]"><QrCode size={17} /></span><div><p className="text-sm font-bold text-white">Authenticity record</p><p className="mt-1 font-mono text-[10px] text-[#91abb4]">SD-2026-8F3C72A19B</p></div></div><span className="rounded-full bg-[#17443d] px-2 py-1 text-[10px] font-bold text-[#94e4cf]">Verified</span></div></div></div></div></div>
      </section>

      <section id="workflows" className="relative border-y border-[#234b58] bg-[#0b2635] py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-2xl"><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#89dcca]">One secure operating model</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.06em] text-white sm:text-5xl">Made for the path from upload to proof</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3"><Feature icon={<LockKeyhole size={20} />} index="01" title="Protect" copy="Validate files, control access, and keep source documents in private storage" /><Feature icon={<FileCheck2 size={20} />} index="02" title="Review" copy="Give managers clear decision points with durable review evidence" /><Feature icon={<QrCode size={20} />} index="03" title="Verify" copy="Issue authenticity records that external viewers can check without seeing private files" /></div></div></section>

      <section id="verification" className="relative mx-auto grid max-w-7xl gap-9 px-6 py-24 lg:grid-cols-[.82fr_1.18fr] lg:px-8"><div className="rounded-[24px] border border-[#315e69] bg-[#103446] p-7 sm:p-9"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#cdf4e8] text-[#137168]"><QrCode size={25} /></div><p className="mt-7 text-[11px] font-extrabold uppercase tracking-[.15em] text-[#9adfcf]">Public verification</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.06em] text-white">Trust can be checked without exposing the document</h2><p className="mt-5 text-sm leading-7 text-[#b0c8cf]">A reference code confirms approved authenticity while keeping private source files, owner identities, and internal metadata protected</p></div><div id="security" className="grid content-center"><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#89dcca]">Security by design</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-.06em] text-white sm:text-5xl">Your workflow is not just visible<br />It is accountable</h2><p className="mt-6 max-w-xl text-base leading-8 text-[#adc5cc]">Use role-aware workspaces, short-lived sessions, audit trails, review gates, and clear security signals to make sensitive document work easier to manage</p><Link href="/workspace" className="mt-8 inline-flex w-fit items-center gap-2 text-sm font-extrabold text-[#8ee1d0]">View the workspace <ArrowRight size={16} /></Link></div></section>
    </main>
  );
}

function Feature({ icon, index, title, copy }: { icon: React.ReactNode; index: string; title: string; copy: string }) {
  return <article className="rounded-2xl border border-[#2a5661] bg-[#102f40] p-6 shadow-[0_12px_35px_rgba(0,0,0,.14)]"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#1b4c58] text-[#91e4d2]">{icon}</span><span className="font-mono text-xs text-[#6f9da6]">{index}</span></div><h3 className="mt-7 text-xl font-extrabold tracking-[-.04em] text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-[#afc7ce]">{copy}</p></article>;
}
